kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 7777
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /home/dplee/work/study/kind-study/dir1
    containerPath: /mydir
- role: worker
  extraMounts:
  - hostPath: /home/dplee/work/study/kind-study/dir2
    containerPath: /mydir
